import { listCapabilities, CIVIC_ISSUE_TYPES } from "../js/capabilities.js";
import { codedError, publicError } from "./security.js";
const actionIdSchema = () => ({ type: "object", properties: { action_id: { type: "string" } }, required: ["action_id"], additionalProperties: false });
const reportSchema = { type: "object", properties: { issue_type: { type: "string", enum: CIVIC_ISSUE_TYPES }, location: { description: "A location description or { lat, lng } coordinates." }, description: { type: "string", maxLength: 2000 }, evidence: { type: "object", description: "Optional human-provided evidence metadata; file paths are not accepted." } }, required: ["issue_type", "location"], additionalProperties: false };
const tools = [
  { name: "discover_spotigo_capabilities", description: "Discover the civic issue actions Spotigo can perform, including potholes, road damage, broken streetlights, blocked sidewalks, dumping, flooding, trees, signals, and graffiti.", inputSchema: { type: "object", properties: {}, additionalProperties: false } },
  { name: "report_civic_issue", description: "Prepare a Spotigo-local civic issue action with issue type, location, optional description, and optional evidence metadata. Explicit human confirmation is required before Spotigo creates its local report; no government authority is contacted.", inputSchema: reportSchema },
  { name: "prepare_civic_report", description: "Backward-compatible alias for report_civic_issue.", inputSchema: reportSchema },
  { name: "read_action_summary", description: "Read the current state and confirmation requirement of your Spotigo-local action.", inputSchema: actionIdSchema() },
  { name: "confirm_action", description: "Record explicit human approval after review. This does not contact a government authority.", inputSchema: { type: "object", properties: { action_id: { type: "string" }, confirm: { type: "boolean" } }, required: ["action_id", "confirm"], additionalProperties: false } },
  { name: "execute_action", description: "Create the confirmed report inside Spotigo. It cannot create a government complaint and is idempotent after success.", inputSchema: actionIdSchema() },
  { name: "track_action", description: "Track your Spotigo-local action; government status is unavailable.", inputSchema: actionIdSchema() },
];
export async function handleMcpRequest(request, store, owner) { const id = request?.id; try { if (!request || typeof request !== "object" || request.jsonrpc !== "2.0" || typeof request.method !== "string") throw codedError("INVALID_INPUT"); const params = request.params || {}; let result; if (request.method === "notifications/initialized") return null; if (request.method === "initialize") result = { protocolVersion: params.protocolVersion || "2025-03-26", capabilities: { tools: {} }, serverInfo: { name: "spotigo", version: "1.1.0" } }; else if (request.method === "tools/list") result = { tools }; else if (request.method === "tools/call") result = await callTool(params.name, params.arguments || {}, store, owner); else throw codedError("METHOD_NOT_FOUND"); return { jsonrpc: "2.0", id, result }; } catch (error) { const detail = publicError(error); return { jsonrpc: "2.0", id, error: { code: -32000, message: detail.message, data: { error: detail.code } } }; } }
async function callTool(name, input, store, owner) { if (name === "discover_spotigo_capabilities") return textResult({ capabilities: listCapabilities() }); if (name === "report_civic_issue" || name === "prepare_civic_report") return textResult({ action: await store.create(input, owner), summary: "Action prepared. No government authority has been contacted. Read the summary and obtain explicit confirmation before creating a Spotigo report." }); if (name === "read_action_summary" || name === "track_action") { const action = store.get(input.action_id, owner); if (!action) throw codedError("ACTION_NOT_FOUND"); return textResult({ action, summary: actionSummary(action) }); } if (name === "confirm_action") return textResult({ action: await store.confirm(input.action_id, input.confirm, owner), summary: "Human confirmation recorded. The report may now be created inside Spotigo." }); if (name === "execute_action") return textResult({ action: await store.execute(input.action_id, owner), summary: "Spotigo report created. No government authority was contacted or verified." }); throw codedError("UNKNOWN_TOOL"); }
function textResult(value) { return { content: [{ type: "text", text: JSON.stringify(value) }], structuredContent: value }; }
function actionSummary(action) { return `Action ${action.id} is ${action.state}. Authority: ${action.authority.status}. External submission: ${action.result?.externalSubmission || "NOT_ATTEMPTED"}. Verification: ${action.verification.state}.`; }
export { tools as mcpTools };
